sequenceDiagram
    participant Journal
    participant Region1
    participant Arbitre
    participant Player
    participant Bridge
    participant Region2


Region1  ->>  Journal:Set(AOI)
Region1  ->>  Arbitre:Set(P*AOI)
Arbitre  ->>  Player:Tick(AOI)
Player   -->> Arbitre:MovedPlayer(Position*Weight)
Arbitre  -->> Region1:Moved(Player*Position*Weight)
Region1  ->>  Bridge:Virtual(Moved(Player*Position*Weight))
Bridge   ->>  Region2:Virtual(Moved(Player*Position*Weight))
