sequenceDiagram
    participant Journal
    participant Region1
    participant Arbitre1
    participant Player
    participant Virtual
    participant Bridge
    participant Region2

Region1  ->>  Journal:Set(P*AOI)
Region1  ->>  Arbitre1:Set(P*AOI)
Arbitre1 ->>  Player:Tick(AOI)
Player   -->> Arbitre1:MovedPlayer(Position*Weight)
Arbitre1 -->> Region1:Moved(Player*Position*Weight)
Region1  ->>  Bridge:TransferPlayer(PlayerState)
Region1  ->>  Region1:Destroy(Player)
Bridge   ->>  Region2:TransferPlayer(PlayerState)