sequenceDiagram
    participant Region
    participant Arbitre
    participant Player1
    participant Player2

Arbitre  ->>   Region:GetEntitiesAOISet
Region  ->> Arbitre:Set(P*AOI)
Arbitre  ->>   Player1:Tick(AOI)
Arbitre  ->>   Player2:Tick(AOI)
Player1 ->> Arbitre:Moved(Position)
Arbitre  ->> Region:Moved(Player1*Position)
Player2 ->> Arbitre:Moved(Position)
Arbitre  ->> Region:Moved(Player2*Position)
Arbitre  ->>  Region:GetEntitiesAOISet
Region  ->>  Region:SolveConflics
Region  ->>  Arbitre:Set(P*AOI)
